name: cert-manager

on:
#   schedule:
#     - cron: '5 * * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync-quay:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TO_USERNAME }}
      TO_PASSWORD: ${{ secrets.TO_PASSWORD }}
    steps:
    - name: Quay to Aliyun
      run: |
        cat << EOF >config.yaml
        registries:
          aliyuncs:
            registry: https://registry.aliyuncs.com
            username: $TO_USERNAME
            password: $TO_PASSWORD
          quay:
            registry: https://quay.io
            repositories:
            - jetstack/cert-manager-cainjector
            - jetstack/cert-manager-webhook
            - jetstack/cert-manager-controller
            - jetstack/cert-manager-ctl
            - jetstack/cert-manager-acmesolver
        sync-policy:
          from: quay
          to: aliyuncs
          dry-run: false
          replace:
            - old: jetstack/
              new: chengccn/
          filters:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
        EOF
        registry-manager sync -c config.yaml
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3
